[features]
seeds = false
skip-lint = false
[programs.localnet]
root_spot_grid = "13uxuLoQHvpp1K1571WcgoTYEV4Ys5ni7LqjBZiTmNNx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dhrumil/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
